import type { Appearance } from "@clerk/types";

// Centralized Clerk appearance aligned to the app's Mocha theme
// Uses warm earthy tones defined in globals.css
export const clerkAppearance: Appearance = {
  variables: {
    colorPrimaryForeground: "#b08968",
    colorPrimary: "#b08968", // mocha sand accent
    colorText: "#f4ede1",
    colorForeground: "#f4ede1",
    colorBackground: "#0e0d0b",
    colorInputBackground: "#1b1917",
    colorInputText: "#f4ede1",
    colorShimmer: "#806a5b",
    colorTextOnPrimaryBackground: "#0e0d0b",
    colorTextSecondary: "#a39282",
    colorDanger: "#ef4444",
    borderRadius: "10px",
    fontFamily: "Geist, ui-sans-serif, system-ui, -apple-system, Segoe UI, Roboto, Helvetica, Arial, Apple Color Emoji, Segoe UI Emoji",
  },
  elements: {
    rootBox: "text-[#f4ede1]",
    card: "bg-white/5 backdrop-blur-sm border border-white/10 shadow-none text-[#f4ede1]",
    cardBox: "text-[#f4ede1]",
    main: "text-[#f4ede1]",
    headerTitle: "text-[#f4ede1]",
    headerSubtitle: "text-[#a39282]",
    logoBox: "hidden",
    footer: "hidden",
    dividerLine: "bg-white/10",
    dividerText: "text-[#a39282]",
    formButtonPrimary:
      "bg-[#b08968] text-[#0e0d0b] hover:bg-[#9b7b58] focus:ring-2 focus:ring-[#b08968]/40 font-semibold",
    formButtonReset: "text-[#a39282] hover:text-[#f4ede1]",
    formFieldInput:
      "bg-[#1b1917] text-[#f4ede1] placeholder:text-[#a39282] border border-white/15 focus:ring-2 focus:ring-[#b08968]",
    formFieldLabel: "text-[#a39282]",
    formFieldInputShowPasswordButton: "text-[#a39282] hover:text-[#f4ede1]",
    formFieldAction: "text-[#b08968] hover:text-[#c97a63]",
    formFieldSuccessText: "text-[#7f8c5a]",
    formFieldErrorText: "text-red-400",
    formFieldInfoText: "text-[#a39282]",
    formFieldWarningText: "text-amber-400",
    formHeaderTitle: "text-[#f4ede1]",
    formHeaderSubtitle: "text-[#a39282]",
    formResendCodeLink: "text-[#b08968] hover:text-[#c97a63]",
    identityPreviewText: "text-[#f4ede1]",
    identityPreviewEditButton: "text-[#a39282] hover:text-[#f4ede1]",
    socialButtons: "bg-[#1b1917] text-[#f4ede1] hover:bg-[#252220] border border-white/15",
    socialButtonsBlockButton: "text-[#f4ede1] hover:bg-[#252220]",
    socialButtonsBlockButtonText: "text-[#f4ede1]",
    socialButtonsIconButton: "text-[#f4ede1] hover:bg-[#252220]",
    avatarBox: "ring-1 ring-white/15",
    footerActionText: "text-[#a39282]",
    footerActionLink: "text-[#b08968] hover:text-[#c97a63]",
    footerPages: "text-[#f4ede1]",
    footerPagesLink: "text-[#b08968] hover:text-[#c97a63]",
    otpCodeFieldInput: "bg-[#1b1917] text-[#f4ede1] border border-white/15",
    alertText: "text-[#f4ede1]",
    formFieldHintText: "text-[#a39282]",
    formFieldOptionalText: "text-[#a39282]",
    modalContent: "text-[#f4ede1]",
    modalCloseButton: "text-[#a39282] hover:text-[#f4ede1]",
    navbarButton: "text-[#f4ede1] hover:bg-[#252220]",
    profileSection: "text-[#f4ede1]",
    profileSectionTitleText: "text-[#f4ede1]",
    profileSectionPrimaryButton: "text-[#b08968] hover:text-[#c97a63]",
    accordionTriggerButton: "text-[#f4ede1] hover:bg-[#252220]",
    badge: "text-[#0e0d0b] bg-[#b08968]",
    // UserButton specific
    userButtonPopoverCard: "bg-[#171411] border border-white/10 text-[#f4ede1]",
    userButtonPopoverMain: "text-[#f4ede1]",
    userButtonPopoverActions: "text-[#f4ede1]",
    userButtonPopoverActionButton: "text-[#f4ede1] hover:bg-[#252220]",
    userButtonPopoverActionButtonText: "text-[#f4ede1]",
    userButtonPopoverActionButtonIcon: "text-[#a39282]",
    userButtonPopoverFooter: "bg-[#171411] border-t border-white/10",
    userPreviewTextContainer: "text-[#f4ede1]",
    userPreviewMainIdentifier: "text-[#f4ede1]",
    userPreviewSecondaryIdentifier: "text-[#a39282]",
    userButtonOuterIdentifier: "text-[#f4ede1]",
    userButtonBox: "text-[#f4ede1]",
    // UserProfile modal
    pageScrollBox: "bg-[#0e0d0b] text-[#f4ede1]",
    page: "bg-[#0e0d0b] text-[#f4ede1]",
    navbar: "bg-[#171411] border-b border-white/10",
    navbarMobileMenuButton: "text-[#f4ede1]",
    navbarMobileMenuRow: "text-[#f4ede1] hover:bg-[#252220]",
    profileSectionContent: "text-[#f4ede1]",
    profileSectionSubtitle: "text-[#a39282]",
    formFieldRow: "text-[#f4ede1]",
    menuList: "bg-[#171411] border border-white/10",
    menuItem: "text-[#f4ede1] hover:bg-[#252220]",
    menuButton: "text-[#f4ede1] hover:bg-[#252220]",
    tagInputContainer: "bg-[#1b1917] border border-white/15",
  },
};

export default clerkAppearance;



